spring:
  profiles.active: development
---
spring:
  profiles: development
  http:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
server:
  contextPath: /api
debug: true
avasec:
  jwt:
    secretkey: secretkey
    sessionTtl: 60
